name: Instano
options:
  bundleIdPrefix: com.xaviernishikawa
  deploymentTarget:
    iOS: "17.0"
targets:
  Instano:
    type: application
    platform: iOS
    sources:
      - path: Instano
        excludes: ["Resources/**"]
      - path: Instano/Resources
        buildPhase: resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.xaviernishikawa.instano
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_CFBundleDisplayName: Instano
        TARGETED_DEVICE_FAMILY: "1"
  InstanoTests:
    type: bundle.unit-test
    platform: iOS
    sources: [InstanoTests]
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: Instano
schemes:
  Instano:
    build:
      targets:
        Instano: all
        InstanoTests: [test]
    test:
      targets: [InstanoTests]
